title: Aergias Documentation
description: The most minimal yet still usable programming language.
remote_theme: just-the-docs/just-the-docs

url: https://las-r.github.io/aergias

aux_links:
  "Aergias on GitHub":
    - https://github.com/las-r/aergias
